http_port: 8001
proxy_port: 9001
connection_timeout: 0
data_dir: "mock_tests"
max_history: 100
proxy_url: ""
assert_headers_pattern: ""
assert_query_params_pattern: ""
cors: '*'
debug: false
aws:
  strip: []
  name: ""
  aws_region: ""
  sign_host: ""
  host: ""
  resign_all_requests: false
  resign_only_expired_date: false
  debug: false
